spring:
  application:
    name: legacy-app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    drop-first: false
  kafka:
    bootstrap-servers: http://localhost:29092
    producer:
      client-id: legacy-app
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: my.home.legacyapp.service.KafkaValueSerializer
      retries: 2
      topic: LEGACY_DB_UPDATE
      key: IN_KEY
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
server:
  port: 8081
logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security.web: DEBUG
